{
	"version": 1693371378,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/play-sheet0.png",
		"images/help-sheet0.png",
		"images/exit-sheet0.png",
		"images/item3-sheet0.png",
		"images/lock-sheet0.png",
		"images/tabstart-sheet0.png",
		"images/tabstart-sheet1.png",
		"images/tiledmap.png",
		"images/floorobj-sheet0.png",
		"images/solidright-sheet0.png",
		"images/solidleft-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground2.png",
		"images/level-sheet0.png",
		"images/level-sheet1.png",
		"images/tiledbackground3.png",
		"images/sprite2-sheet0.png",
		"images/flo-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/door-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/player-sheet0.png",
		"images/itemr-sheet0.png",
		"images/iten-sheet0.png",
		"images/iten-sheet1.png",
		"images/health-sheet0.png",
		"images/hp-sheet0.png",
		"images/coss-sheet0.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/roce-sheet0.png",
		"images/tiledbackground6.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/mon-sheet0.png",
		"images/mon-sheet1.png",
		"images/btn_left1-sheet0.png",
		"images/player2-sheet0.png",
		"images/particles.png",
		"images/score-sheet0.png",
		"images/fadestart-sheet0.png",
		"images/fadests-sheet0.png",
		"images/tiledbackground7.png",
		"images/tiledbackground8.png",
		"images/tiledbackground9.png",
		"images/bg-sheet0.png",
		"images/tiledbackground10.png",
		"images/bg2-sheet0.png",
		"images/bat-sheet0.png",
		"images/bat-sheet1.png",
		"images/bullet1-sheet0.png",
		"images/freobj-sheet0.png",
		"images/freobj-sheet1.png",
		"images/freobj-sheet2.png",
		"images/over-sheet0.png",
		"images/gifbg-sheet0.png",
		"images/gifbg-sheet1.png",
		"images/gifbg-sheet2.png",
		"images/sprite16-sheet0.png",
		"images/bg5-sheet0.png",
		"images/bg5-sheet1.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/next-sheet0.png",
		"images/bg6-sheet0.png",
		"images/bg6-sheet1.png",
		"images/bg6-sheet2.png",
		"images/sprite21-sheet0.png",
		"images/boss-sheet0.png",
		"images/portal-sheet0.png",
		"images/portal-sheet1.png",
		"images/bg02-sheet0.png",
		"images/powershot-sheet0.png",
		"images/boobpower-sheet0.png",
		"images/boobpower-sheet1.png",
		"images/back-sheet0.png",
		"images/back2-sheet0.png",
		"images/bg11-sheet0.png",
		"images/bg11-sheet1.png",
		"images/bg11-sheet2.png",
		"images/bggif1-sheet0.png",
		"images/bggif1-sheet1.png",
		"images/bggif1-sheet2.png",
		"images/sprite23-sheet0.png",
		"images/bggif2-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite27-sheet1.png",
		"images/sprite27-sheet2.png",
		"images/sprite27-sheet3.png",
		"images/sprite27-sheet4.png",
		"images/sprite29-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/buboss2-sheet0.png",
		"images/buboss2-sheet1.png",
		"images/boobpl-sheet0.png",
		"images/doorboos3-sheet0.png",
		"images/doorboos3-sheet1.png",
		"images/doorboos3-sheet2.png",
		"images/doorboos3-sheet3.png",
		"images/doorboos3-sheet4.png",
		"images/doorboos3-sheet5.png",
		"images/bock-sheet0.png",
		"images/doorboss-sheet0.png",
		"images/b-sheet0.png",
		"images/b-sheet1.png",
		"images/b-sheet2.png",
		"images/b-sheet3.png",
		"images/b-sheet4.png",
		"images/b-sheet5.png",
		"images/b-sheet6.png",
		"images/b-sheet7.png",
		"images/b-sheet8.png",
		"images/b-sheet9.png",
		"images/b-sheet10.png",
		"images/b1-sheet0.png",
		"images/b1-sheet1.png",
		"images/b1-sheet2.png",
		"images/b1-sheet3.png",
		"images/b1-sheet4.png",
		"images/sprite33-sheet0.png",
		"images/sprite33-sheet1.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite41-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite51-sheet0.png",
		"images/sprite52-sheet0.png",
		"images/hppbar-sheet0.png",
		"media/anyconv.com__desert theme.m4a",
		"media/anyconv.com__desert theme.ogg",
		"media/anyconv.com__mushroom theme.m4a",
		"media/anyconv.com__mushroom theme.ogg",
		"media/jump_04.m4a",
		"media/jump_04.ogg",
		"media/jump_09.m4a",
		"media/jump_09.ogg",
		"media/anyconv.com__relic attack 5.m4a",
		"media/anyconv.com__relic attack 5.ogg",
		"media/foom_0.m4a",
		"media/foom_0.ogg",
		"media/anyconv.com__walk_in_the_twilight_forest_music.m4a",
		"media/anyconv.com__walk_in_the_twilight_forest_music.ogg",
		"media/of far different nature - horny (cc-by).m4a",
		"media/of far different nature - horny (cc-by).ogg",
		"media/anyconv.com__of far different nature - scene - epic departure (cc-by).m4a",
		"media/anyconv.com__of far different nature - scene - epic departure (cc-by).ogg",
		"media/juhani junkala - epic boss battle [seamlessly looping].m4a",
		"media/juhani junkala - epic boss battle [seamlessly looping].ogg",
		"media/anyconv.com__little town - orchestral.m4a",
		"media/anyconv.com__little town - orchestral.ogg",
		"media/anyconv.com__a big adventure.m4a",
		"media/anyconv.com__a big adventure.ogg",
		"media/the_little_big_adventure_.ogg",
		"media/anyconv.com__00_-_legit_audio_-_legit_fir_fire_staff_20-audio.m4a",
		"media/anyconv.com__00_-_legit_audio_-_legit_fir_fire_staff_20-audio.ogg",
		"media/anyconv.com__punch-140236.m4a",
		"media/anyconv.com__punch-140236.ogg",
		"media/anyconv.com__closing door.m4a",
		"media/anyconv.com__closing door.ogg",
		"media/anyconv.com__closing door (mp3cut.net).m4a",
		"media/anyconv.com__closing door (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}